# Use a Java runtime as base image
FROM openjdk:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven
COPY target/D387_sample_code-0.0.2-SNAPSHOT.jar /app/app.jar

# Expose port 8080
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]